name: Terraform CI/CD

on:
  schedule:
    - cron: '15 10 * * *'  # Runs every day at 8:00 AM UTC for apply
    - cron: '25 10 * * *' # Runs every day at 8:00 PM UTC for destroy

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.schedule == '15 10 * * *' # Apply only on main branch at 8:00 AM
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Update this to your region if different

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -out=plan.out

      - name: Terraform Apply
        run: terraform apply -auto-approve plan.out

  terraform_destroy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.schedule == '25 10 * * *' # Destroy only on main branch at 8:00 PM
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1 # Update this to your region if different

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
