name: Terraform CI/CD

on:
  push:
    branches:
      - main
  schedule:
    - cron: '32 16 * * *'  # Runs every day at 10:00 PM UTC

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checko
